{% set packagename = 'legit' %}
{% set version = "1.0.0" %}
{% set sha256 = "53a67ad7a7caefab7a6c28a76d7967022e2aee956993b1b074cc4d8c78cc1500" %}

package:
  name: {{ packagename }}
  version: {{ version }}

source:
  fn: {{ packagename }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pakcagename[0] }}/{{ packagename }}/{{ packagename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - legit = legit.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - args
    - click
    - clint
    - crayons
    - gitdb2
    - gitpython
    - packaging
    - six
    - smmap2
    - gitpython
    - six

test:
  imports:
    - legit

  commands:
    - legit --version

about:
  home: https://github.com/kennethreitz/legit
  license: BSD-3
  license_file: LICENSE
  summary: 'Git for Humans.'
  dev_url: https://github.com/kennethreitz/legit

extra:
  recipe-maintainers:
    - ericmjl
