{% set version = "1.1.0" %}

package:
  name: legit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/legit/legit-{{ version }}.tar.gz
  sha256: 25bd3809d657c9b0bd45a6a230dc7f58a56e6e068159d471ffeadb0cf4677b4d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - legit = legit.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - clint
    - crayons
    - gitpython
    - six

test:
  imports:
    - {{ packagename }}
  commands:
    - mkdir test-git-repo
    - cd test-git-repo
    - git init
    # legit needs a remote or it exits with a non-zero status
    # so we just need to add a fake one
    - git remote add origin http://
    - legit help
  requires:
    - git

about:
  home: https://github.com/kennethreitz/legit
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Git for Humans'

extra:
  recipe-maintainers:
    - ericmjl
