{% set version = "1.2.0.post0" %}

package:
  name: legit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/legit/legit-{{ version }}.tar.gz
  sha256: 949396b68029a8af405ab20c901902341ef6bd55c7fec6dab71141d63d406b11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - legit = legit.cli:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - clint
    - click
    - crayons
    - gitpython
    - six

test:
  imports:
    - legit
  commands:
    - mkdir test-git-repo
    - cd test-git-repo
    - git init
    # legit needs a remote or it exits with a non-zero status
    # so we just need to add a fake one
    - git remote add origin http://
    - legit -h
  requires:
    - git

about:
  home: https://github.com/kennethreitz/legit
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Git for Humans

extra:
  recipe-maintainers:
    - ericmjl
