{% set packagename = 'legit' %}
{% set version = "0.4.1" %}
{% set md5 = "3917e991e72004406bd51ed1881b71d1" %}

package:
  name: {{ packagename }}
  version: {{ version }}

source:
  git_url: https://github.com/kennethreitz/legit
  git_tag: v{{ version }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - legit = legit.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - clint
    - gitpython
    - six

test:
  imports:
    - {{ packagename }}

  commands:
    - mkdir test-git-repo
    - cd test-git-repo
    - git init
    # legit needs a remote or it exits with a non-zero status
    # so we just need to add a fake one
    - git remote add origin http://
    - legit help
  requires:
    - git

about:
  home: https://github.com/kennethreitz/legit
  license: BSD-3
  summary: 'Git for Humans.'

extra:
  recipe-maintainers:
    - ericmjl
