travis:
  secure:
    BINSTAR_TOKEN: R/QyDTK0JQotFC0kVLR4afeGPkB2yZAu7QPhlQqAKy0/+E2aPxteK64cULtWJdsBYxewJpiJEzUBcS+i47+AI5rVa/G/Sy9HrC13TI5Bwj63OB5+g/twQsaNo5WViSJ3uVi4mCTBD9BiHpn0eTEeC1p0AuDwCPWoW0TPQNll3NhfsAuzbZUg/+hs/IAcf+3txoqpJUAQJeTsOmsN7vVowtkssTxdaR988sOPXRsYzolVBuDTUGa92NacFJTCbjPR4gLhukY+29cpuapL/72DrV/yU6n2JU2aKjLPW2HXVQyUQx7TyF3c+K7EVYTM09yTMWaJdO6Z3w6Gq+CI5VgN3MIz5IKhotYv/kAYrCPnftGWJ74lJtw7321vCOmH6bv/XoWcfcgNc486cwO4/yPw2jhwTXDh0B952LUVozFCkCpTEI7H5znfYEhI3oKAfcotISlP8cNcP5Ml2U/39r0DmQTtDPXFBL9f6tJBHdA75JEwHZWV3G4gkz3zWR3F8qClo0/brOjVRWdqM5gdnpcbqa9aB1Go7nLtkt6wfz3vI5SigHISHb0C4FzA/PMU6dSCCNWDWkIBBMfV/4S6IDrBs60RJC39BgVNcaNHsMK0bLxPayRIIt1y/3h67ZELbHZtC2Acrw8EPK4fmCufjUqtzpzj/kwoQOQdwmOGo6t2ndc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
