appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NSOhz4hMA6gAxyk1p7AyShPLc1LNFyXJ4mxuniqnEyA9jnI1xmZkYez3ZGsgNmhlmqTR1bv9jEOjuEIDVypxoVj3K2RZ++MJaobizKJIVF12lP490MOhK7Sd0QRPkr3fQrmcx+qzjrNQIRZdsv9H4URoLiHZ12ym8Pfql3rvVkcXtIHkexnZOqGUrW7THkke652sXnOcyOhjKXyCNeUenSlwpD6tRvFHGl1AVRQZV5IPoKad827IjVydcSxA4suvZlORTmBRZpHElPtVLD1iezkEOOAX/kNw1kAjVIuWZyA8c46/bxjz+q03F7KauR9Uzduj83Z9p0LIT199lQlQKncSBzrG/FyF6BzlseizkWgEWn2igob3+78XHL1TMoMj0QTzsEEqyynE3vvwfkaE8RDYtoVH940ELkr46HQJS666Qf5UdGTIONTgMFerAn2P4hJwMx8IJb6zH5IsKRJOhSpCw4s+6NMv/sijh/Li1/aW+GLXsPUAd8COfA2O5PdHDEZ64RQBsMWAzgSWRL5PdyXFJYgr8l6pgoRfvVe/hiT4xQune2qFQIbvXjP5vJKSGqFblm+LCA6cEf3iEy/R2zLMqYr6gpj9W+FVn6dGh7GSv6HP/ahNFX5KK532izo4WBRlNCurcqrTHYtS52D8J3u/w+qOnb6cxKpejhbckDE=}
